#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements
cp /etc/hosts /etc/hosts.bak
sed -i 's/^127.0.0.1\s\+localhost$/127.0.0.2 localhost/g' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
cat /etc/hosts
